---
version: "3"
services:
  mongodb:
    container_name: "mongodb"
    image: "mongo:latest"
    environment:
      MONGO_INITDB_ROOT_USERNAME: cyb3rgh05t
      MONGO_INITDB_ROOT_PASSWORD: 9ffe4e761f
    networks:
      - proxy
    security_opt:
      - "no-new-privileges:true"
    labels:
      - "dockupdater.enable=false"
    restart: "${RESTARTAPP}"
    volumes:
      - mongodb_data:/data/db

  discordbot:
    hostname: "mr_streamnet"
    container_name: "mr_streamnet"
    environment:
      - "PGID=1000"
      - "PUID=1000"
      - "TZ=Europe/Berlin"
    networks:
      - proxy
    security_opt:
      - "no-new-privileges:true"
    labels:
      - "dockupdater.enable=false"
    image: "ghcr.io/cyb3rgh05t/mr.streamnet_lite:latest"
    stdin_open: true # docker run -i
    tty: true # docker run -t
    restart: "unless-stopped"
    volumes:
      - "opt/appdata/mr.streamnet/:/app/bot/src/config:rw"
    depends_on:
      - mongodb
    links:
      - mongodb:db

volumes:
  mongodb_data:

networks:
  proxy:
    driver: bridge
    external: true
