version: "3"
services:
  discord-bot:
    hostname: "discord-bot"
    container_name: "discord-bot"
    environment:
      - "PGID=${ID}"
      - "PUID=${ID}"
      - "TZ=${TZ}"
      - "UMASK=${UMASK}"
    image: "ghcr.io/cyb3rgh05t/discord-bot:latest"
    restart: "${RESTARTAPP}"
    networks:
      - ${DOCKERNETWORK}
    security_opt:
      - "${SECURITYOPS}:${SECURITYOPSSET}"
    volumes:
      - "${APPFOLDER}/discord-bot/config:/app/config:rw"
      - "${APPFOLDER}/discord-bot/databases:/app/databases:rw"
    labels:
      - "dockupdater.enable=true"
      - "com.centurylinklabs.watchtower.enable=true"
networks:
  proxy:
    driver: bridge
    external: true
