version: "3"
services:
  telegram_bot:
    hostname: "discord-bot"
    container_name: "discord-bot"
    environment:
      - "PGID=${ID}"
      - "PUID=${ID}"
      - "TZ=${TZ}"
      - "UMASK=${UMASK}"
    image: "ghcr.io/cyb3rgh05t/discord-bot:latest"
    restart: "${RESTARTAPP}"
    ports:
      - "8000:8000/tcp"
    networks:
      - ${DOCKERNETWORK}
    security_opt:
      - "${SECURITYOPS}:${SECURITYOPSSET}"
    volumes:
      - "${APPFOLDER}/discord-bot/config:/app/config:rw"
      - "${APPFOLDER}/discord-bot/databases:/app/databases:rw"
    labels:
      - "dockupdater.enable=true"
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.botpanel-rtr.entrypoints=https"
      - "traefik.http.routers.botpanel-rtr.rule=Host(`botpanel.${DOMAIN}`)"
      - "traefik.http.routers.botpanel-rtr.tls=true"
      - "traefik.http.routers.botpanel-rtr.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.botpanel-rtr.middlewares=chain-authelia@file"
      - "traefik.http.routers.botpanel-rtr.service=botpanel-svc"
      - "traefik.http.services.botpanel-svc.loadbalancer.server.port=8000"

networks:
  proxy:
    driver: bridge
    external: true
