---
version: "3"
services:
  mongodb:
    container_name: "streamnet-mongodb"
    image: "mongo:latest"
    environment:
      MONGO_INITDB_ROOT_USERNAME: cyb3rgh05t
      MONGO_INITDB_ROOT_PASSWORD: 9ffe4e761f
    networks:
      - ${DOCKERNETWORK}
    security_opt:
      - "${SECURITYOPS}:${SECURITYOPSSET}"
    labels:
      - "dockupdater.enable=false"
    restart: "${RESTARTAPP}"
    volumes:
      - mongodb_data:/data/db

  discordbot:
    hostname: "mr_streamnet"
    container_name: "mr_streamnet"
    environment:
      - "PGID=${ID}"
      - "PUID=${ID}"
      - "TZ=${TZ}"
    networks:
      - ${DOCKERNETWORK}
    security_opt:
      - "${SECURITYOPS}:${SECURITYOPSSET}"
    labels:
      - "dockupdater.enable=false"
    image: "ghcr.io/cyb3rgh05t/mr.streamnet_lite:latest"
    stdin_open: true # 
    tty: true        # docker run -t
    restart: "${RESTARTAPP}"
    volumes:
      - "${APPFOLDER}/mr.streamnet/:/app/bot/src/config:rw"
    depends_on:
      - mongodb
    links:
      - mongodb:db

volumes:
  mongodb_data:

networks:
  proxy:
    driver: bridge
    external: true
