---
version: "3"
services:
  mongodb:
    container_name: "streamnet-mongodb"
    image: "mongo:latest"
    environment:
      MONGO_INITDB_ROOT_USERNAME: cyb3rgh05t
      MONGO_INITDB_ROOT_PASSWORD: 9ffe4e761f
    networks:
      - ${DOCKERNETWORK}
    security_opt:
      - "${SECURITYOPS}:${SECURITYOPSSET}"
    labels:
      - "dockupdater.enable=false"
    restart: "${RESTARTAPP}"
    volumes:
      - mongodb_data:/data/db

  lavalink:
    container_name: "lavalink"
    image: "ghcr.io/cyb3rgh05t/lavalink:latest"
    restart: "${RESTARTAPP}"
    environment:
      - "PGID=${ID}"
      - "PUID=${ID}"
      - "TZ=${TZ}"
    networks:
      - ${DOCKERNETWORK}
    security_opt:
      - "${SECURITYOPS}:${SECURITYOPSSET}"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "dockupdater.enable=false"
      - "traefik.http.routers.lavalink-rtr.entrypoints=https"
      - "traefik.http.routers.lavalink-rtr.rule=Host(`lavalink.${DOMAIN}`)"
      - "traefik.http.routers.lavalink-rtr.tls=true"
      - "traefik.http.routers.lavalink-rtr.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.lavalink-rtr.middlewares=chain-authelia@file"
      - "traefik.http.routers.lavalink-rtr.service=lavalink-svc"
      - "traefik.http.services.lavalink-svc.loadbalancer.server.port=2333"

  discordbot:
    hostname: "mr_streamnet"
    container_name: "mr_streamnet"
    environment:
      - "PGID=${ID}"
      - "PUID=${ID}"
      - "TZ=${TZ}"
    networks:
      - ${DOCKERNETWORK}
    security_opt:
      - "${SECURITYOPS}:${SECURITYOPSSET}"
    labels:
      - "dockupdater.enable=false"
    image: "ghcr.io/cyb3rgh05t/mr.streamnet:latest"
    restart: "${RESTARTAPP}"
    volumes:
      - "/opt/appdata/discordbot/config:/bot/streamnet/src/:rw"
    depends_on:
      - mongodb
      - lavalink
    links:
      - mongodb:db
      - lavalink

volumes:
  mongodb_data:

networks:
  proxy:
    driver: bridge
    external: true
